# use the setting below to set multiple docs directories.
# docSections = ["docs", "tutorials"]

uniqueHomePage = true # change to false to add sidebar to homepage

repo = "https://github.com/davidgf/superfw-docs"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = false # set to false to disable darkmode by default # user will still have the option to use dark mode
defaultLightingMode = "auto" # other possible values: "dark", "light"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 10

# show/hide line numbers by default. Switch to `true` if you'd rather have them on.
showLineNumbers = false

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

# Enable copyRight Footer Stamp. Takes in attribution
enableCopyright = true

# search
[search]
on = false
global = false # turn to `true` to enable global search

# Site logo
[logo]
  lightMode = "images/superfw-logo.svg"
  darkMode = "images/superfw-logo.svg"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/davidgf/superfw-docs"

[author]
  name = "davidgf.net"
  url = "https://www.davidgf.net/"

[params]
  customCSS = ["css/custom.css"]

